### PR TITLE
feat:Allow skipping of the Git pull before tagging

### LINKED ISSUE #143: Is there a way to skip the Git Pull?
Is there a way to skip doing the Git Pull? 
I always ensure that I do a checkout [with all history and branches](https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches) so I do not need the extra pull. 
It is actually quite harmful where I want to be able to build my commit on a merge to `main` and then tag and release using this action. 
However if someone else merges to `main` while my commit is build then I will end up tagging and releasing the wrong commit as this extra pull will pull in the extra changes that are not part of my build.

Hope this makes sense let me know if it doesn't or if I am missing something!!

### PR DESCRIPTION
**Pull request by apr-1985**
Resolves https://github.com/TriPSs/conventional-changelog-action/issues/143

### CODE REVIEW

**Comment by TriPSs** [comment]
Thanks for the PR! Could you also add a test case for this feature?

**Comment by apr-1985** [comment]
> Thanks for the PR! Could you also add a test case for this feature?

I can't think of a way to test the functionality per se as it would require a process committing to the upstream branch  which cant really happen in a single actions workflow and the fact that git stuff is blocked in the test env anway.
https://github.com/TriPSs/conventional-changelog-action/blob/ae41970cdd2ce5ec45846bbfc94438621402ffdd/src/helpers/git.js#L23.

However I have added a "regression" test case to ensure using the option doesn't break anything over not using it.

**Comment by TriPSs** [comment]
@apr-1985 sorry for the late reply, but it can be added [here](https://github.com/TriPSs/conventional-changelog-action/blob/releases%2Fv3/src/helpers/git.js#L162).

**Comment by apr-1985** [comment]
> @apr-1985 sorry for the late reply, but it can be added [here](https://github.com/TriPSs/conventional-changelog-action/blob/releases%2Fv3/src/helpers/git.js#L162).

Thanks for the pointer I have added the full test case.  Let me know if you want me to rebase down to a single commit or if you squash.

**Comment by apr-1985** [comment]
Hope all is well. Is this waiting on anything from me to go in?

**Comment by TriPSs** [comment]
@apr-1985 no sorry, will check everything asap and release it :)

**Comment by apr-1985** [comment]
> @apr-1985 no sorry, will check everything asap and release it :) 

No problem at all. Was worried I had missed something. That's usually the way 😀

**Pull request merged**
